scan_filter_chain:
- name: scan_range
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.1
    upper_threshold: 3.5
    use_message_range_limits: false
    lower_replacement_value: 3.4
    upper_replacement_value: 3.4